const data = [
  {
    productId: "e25bf455-0b9d-4f0d-8b44-2a5f6853f6d1",
    name: "Cool T-Shirt 1",
    liked: "no",
    description: "A stylish and comfortable t-shirt for everyday wear.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/t-shirt1-pic1.jpg",
      "https://example.com/t-shirt1-pic2.jpg",
    ],
  },
  {
    productId: "a4dc875c-2a9f-4e01-8e3d-f4d39920a56b",
    name: "Awesome Shirt 2",
    liked: "yes",
    description:
      "A classic shirt suitable for both formal and casual occasions.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/shirt2-pic1.jpg",
      "https://example.com/shirt2-pic2.jpg",
    ],
  },
  {
    productId: "c51f4b1e-1f7e-431a-9e0f-7c3667f1c918",
    name: "Funky Tank Top 3",
    liked: "no",
    description: "A vibrant and trendy tank top for a stylish summer look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/tank-top3-pic1.jpg",
      "https://example.com/tank-top3-pic2.jpg",
    ],
  },
  {
    productId: "50b88de3-aa47-45f7-99f4-8ea31663c2a1",
    name: "Classic Blue T-Shirt",
    liked: "no",
    description: "A comfortable blue t-shirt for everyday wear.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/blue-t-shirt-pic1.jpg",
      "https://example.com/blue-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "f3e4e18e-d5d9-47f5-a3c9-6c1e9914f8c4",
    name: "Casual Striped Shirt",
    liked: "no",
    description: "A stylish striped shirt for a relaxed look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/striped-shirt-pic1.jpg",
      "https://example.com/striped-shirt-pic2.jpg",
    ],
  },
  {
    productId: "18d9930b-7d5e-494a-a752-26e5e2b3f58f",
    name: "Summer Tank Top",
    liked: "no",
    description: "A lightweight tank top perfect for hot summer days.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/summer-tank-top-pic1.jpg",
      "https://example.com/summer-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "eac32aeb-5032-4f97-93c2-7efeb2a99142",
    name: "Graphic Print T-Shirt",
    liked: "no",
    description: "A trendy t-shirt with a unique graphic print design.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/graphic-t-shirt-pic1.jpg",
      "https://example.com/graphic-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "f6c67f88-b063-4b65-8c2b-cf6c1395c96e",
    name: "Formal White Shirt",
    liked: "no",
    description: "A crisp white shirt suitable for formal occasions.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/white-shirt-pic1.jpg",
      "https://example.com/white-shirt-pic2.jpg",
    ],
  },
  {
    productId: "e7f2a65e-5a2a-4ac7-ae02-0d3bba3a99d9",
    name: "Floral Tank Top",
    liked: "no",
    description: "A floral patterned tank top for a fun and vibrant look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/floral-tank-top-pic1.jpg",
      "https://example.com/floral-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "8bf44d6d-6f2d-4c3c-9e33-2e4c8a9cf9dd",
    name: "Geometric Print T-Shirt",
    liked: "no",
    description:
      "A t-shirt featuring a geometric print pattern for a modern look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/geometric-t-shirt-pic1.jpg",
      "https://example.com/geometric-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "2a9de073-cfe6-45b5-90ec-e09b4139b3b5",
    name: "Denim Shirt",
    liked: "no",
    description: "A denim shirt with a rugged and casual style.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/denim-shirt-pic1.jpg",
      "https://example.com/denim-shirt-pic2.jpg",
    ],
  },
  {
    productId: "c8b6355f-6e82-44e1-9312-2431e86ac498",
    name: "Striped Tank Top",
    liked: "no",
    description: "A striped tank top for a nautical-inspired look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/striped-tank-top-pic1.jpg",
      "https://example.com/striped-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "a1e59bf1-33d8-4a86-925f-fb3a9f9e2c22",
    name: "Vintage T-Shirt",
    liked: "no",
    description: "A vintage-inspired t-shirt with a retro design.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/vintage-t-shirt-pic1.jpg",
      "https://example.com/vintage-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "5ec6c27b-91e1-4d2c-ba7e-e29f7d6eb58c",
    name: "Linen Shirt",
    liked: "no",
    description: "A breathable linen shirt perfect for summer outings.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/linen-shirt-pic1.jpg",
      "https://example.com/linen-shirt-pic2.jpg",
    ],
  },
  {
    productId: "cbf77c48-3b49-41d8-88f7-36a7038477df",
    name: "Beachy Tank Top",
    liked: "no",
    description: "A beach-themed tank top for a relaxed coastal vibe.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/beachy-tank-top-pic1.jpg",
      "https://example.com/beachy-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "b05c1a3f-e6c2-4f48-87f0-1f4a931fa9c7",
    name: "Sports T-Shirt",
    liked: "no",
    description: "A performance-oriented t-shirt for sports and workouts.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/sports-t-shirt-pic1.jpg",
      "https://example.com/sports-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "a7b0e01a-7320-4956-90a0-8289a9a8b79e",
    name: "Plaid Flannel Shirt",
    liked: "no",
    description: "A cozy plaid flannel shirt for a rustic look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/plaid-flannel-shirt-pic1.jpg",
      "https://example.com/plaid-flannel-shirt-pic2.jpg",
    ],
  },
  {
    productId: "9d121f43-dfb6-4edf-a3f9-5dca2d6f9a0a",
    name: "Retro Tank Top",
    liked: "no",
    description: "A retro-style tank top with a bold color palette.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/retro-tank-top-pic1.jpg",
      "https://example.com/retro-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "d20e3e95-6a19-4fcd-b52f-8b738e5df1c9",
    name: "Gaming T-Shirt",
    liked: "no",
    description: "A gaming-themed t-shirt for gamers and enthusiasts.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/gaming-t-shirt-pic1.jpg",
      "https://example.com/gaming-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "f992d79f-2c44-4b16-8895-df4fc60e03cf",
    name: "Cotton Oxford Shirt",
    liked: "no",
    description: "A classic cotton oxford shirt for a polished look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/cotton-oxford-shirt-pic1.jpg",
      "https://example.com/cotton-oxford-shirt-pic2.jpg",
    ],
  },
  {
    productId: "c9d6e70a-7434-44d8-a7ef-9423b60c501a",
    name: "Neon Tank Top",
    liked: "no",
    description: "A vibrant neon tank top for a bold fashion statement.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/neon-tank-top-pic1.jpg",
      "https://example.com/neon-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "8e1a76b9-9d76-43aa-9e60-5c365edcc663",
    name: "Music Festival T-Shirt",
    liked: "no",
    description: "A t-shirt featuring a music festival-inspired design.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/music-festival-t-shirt-pic1.jpg",
      "https://example.com/music-festival-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "bf4d78fc-8f67-4be5-a1d2-38f2a2d6f650",
    name: "Linen Button-Up Shirt",
    liked: "no",
    description:
      "A breathable linen button-up shirt for a casual yet refined look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/linen-button-up-shirt-pic1.jpg",
      "https://example.com/linen-button-up-shirt-pic2.jpg",
    ],
  },
  {
    productId: "62c6d69f-1e7c-485d-bc2e-abb70b789a4e",
    name: "Tropical Tank Top",
    liked: "no",
    description: "A tropical-themed tank top for a vacation-ready style.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/tropical-tank-top-pic1.jpg",
      "https://example.com/tropical-tank-top-pic2.jpg",
    ],
  },
  {
    productId: "d2be016f-772e-4bae-aa4a-45ca5f22b1c0",
    name: "Vintage Rock Band T-Shirt",
    liked: "no",
    description: "A vintage rock band t-shirt for music enthusiasts.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "t-shirt",
    pictures: [
      "https://example.com/vintage-rock-band-t-shirt-pic1.jpg",
      "https://example.com/vintage-rock-band-t-shirt-pic2.jpg",
    ],
  },
  {
    productId: "aa0d3aeb-d070-4c57-bf2b-4e08895a5f38",
    name: "Checkered Flannel Shirt",
    liked: "no",
    description: "A checkered flannel shirt for a cozy and casual look.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "shirt",
    pictures: [
      "https://example.com/checkered-flannel-shirt-pic1.jpg",
      "https://example.com/checkered-flannel-shirt-pic2.jpg",
    ],
  },
  {
    productId: "bd3ea0c5-578e-407e-a5a0-6191c76475d3",
    name: "Minimalist Tank Top",
    liked: "no",
    description: "A minimalist tank top with clean lines and a modern design.",
    owner: {
      userId: "a87cda11-7e98-4b24-9b7c-02302f0b1563",
      weightInKilos: 92,
      name: "André Treib",
      heightInCentimeters: 186,
      bodyType: "muscular",
    },
    type: "tank top",
    pictures: [
      "https://example.com/minimalist-tank-top-pic1.jpg",
      "https://example.com/minimalist-tank-top-pic2.jpg",
    ],
  },
];

export { data };
